music/models/song.py
class Song:
    def __init__(self, artist, title, year, web_url, img_url=None):
        self.artist = artist
        self.title = title
        self.year = year
        self.web_url = web_url
        self.img_url = img_url

music/models/user.py
from flask_login import UserMixin

class User(UserMixin):

    def __init__(self, id, email, username, password, usersongs):
        self.id = id
        self.email = email
        self.username = username
        self.password = password
        self.usersongs = usersongs

music/routes/forms.py
from boto3.docs.docstring import AttributeDocstring
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, PasswordField
from flask_wtf.file import FileField, FileRequired
from wtforms.validators import DataRequired

from ..db.authentication import check_email_unique, check_password

class PostForm(FlaskForm):
    subject = StringField('Subject', validators=[DataRequired()])
    message = TextAreaField('Message', validators=[DataRequired()])
    image = FileField('Image', validators=[FileRequired()])
    submit = SubmitField('Post')

class RegisterForm(FlaskForm):
    email = StringField('email', validators=[DataRequired()])
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField('register')

    def validate(self):

        if not FlaskForm.validate(self):
            return False
        else:

            if not check_email_unique(self.email.data):
                self.email.errors.append('The email already exists')
                return False

            return True

class LoginForm(FlaskForm):
    email = StringField('email', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField('login')

    def validate(self):

        if not FlaskForm.validate(self):
            return False
        else:

            if check_password(self.email.data, self.password.data):
                return True

            self.password.errors.append('email or password is invalid')
            return False

class QueryForm(FlaskForm):
    artist = StringField('artist') 
    title = StringField('title')
    year = StringField('year')
    search = SubmitField('query')

music/__init__.py
import os

from flask import Flask
from flask_login import login_manager, login_user, logout_user, login_required, current_user, LoginManager

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(SECRET_KEY='dev')

    loginManager = LoginManager(app)
    loginManager.login_view = 'authentication/login'

    from .routes import authentication, subscription, index
    app.register_blueprint(authentication.bp)
    app.register_blueprint(subscription.bp)
    app.register_blueprint(index.bp)

    from .db import dynamodb, s3
    dynamodb.init_app(app)
    s3.init_app(app)    

    @loginManager.user_loader
    def load_user(id):
        return dynamodb.get_user(id)

    return app

music/routes/__init__.py
pass

music/routes/authentication.py
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from flask_login import login_user, logout_user, login_required, current_user

from ..db.dynamodb import get_user, put_user
from .forms import LoginForm, RegisterForm

bp = Blueprint('authentication', __name__, url_prefix='/authentication')

@bp.route('/register', methods=('GET', 'POST'))
def register():

    form = RegisterForm()

    if request.method == 'POST':

        if form.validate_on_submit():
            put_user(form.email.data, form.username.data, form.password.data, [])
            return redirect(url_for('authentication.login'))

        else:
            return render_template('authentication/register.html', current_user=current_user, form=form)

    else:
        return render_template('authentication/register.html', current_user=current_user, form=form)


@bp.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()

    if request.method == 'POST':

        if form.validate_on_submit():
            login_user(get_user(form.email.data))
            return redirect(url_for('subscription.music'))

        else:
            return render_template('authentication/login.html', current_user=current_user, form=form)   

    else:
        return render_template('authentication/login.html', current_user=current_user, form=form)   

@bp.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

music/routes/index.py
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for, g
from flask_login import current_user

from ..db.dynamodb import get_user, put_user, get_users, get_song, get_songs

bp = Blueprint('', __name__)

@bp.route('/')
@bp.route('/index')
def index():

    return render_template('index.html', current_user=current_user)

music/routes/subscription.py
import os

from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from flask_login import current_user

from ..db.s3 import get_img
from ..db.dynamodb import get_songs, get_user_songs, rm_user_song, put_user_song
from .forms import QueryForm

bp = Blueprint('subscription', __name__, url_prefix='/subscription')

#@bp.route('/music/<query_songs>', methods=["GET"])
@bp.route('/music', methods=["GET"])
def music():
    form = QueryForm()

        # set up query_songs
    #query_songs = []
    #get_songs()
    # get user songs and images:
    user_songs = get_user_songs(current_user.email) #list

    # If we're local, use place holder images.
    if os.environ['FLASK_ENV'] == "dev":
            for song in user_songs:
                song.img_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Test-Logo.svg/783px-Test-Logo.svg.png"
    else:
        for song in user_songs:
            song.img_url = get_img(song.artist)

    return render_template('subscription/music.html', current_user=current_user, user_songs=user_songs, form=form)


@bp.route('/music/remove', methods=["POST"])
def remove():

    # parse request
    print(f"Removing: {request.form['artist']}:{request.form['title']}")

    # remove song 
    rm_user_song(current_user.email, request.form['artist'], request.form['title'])

    # redirect to music
    return redirect(url_for('subscription.music'))

@bp.route('/music/subscribe', methods=["POST"])
def subscribe():

    # parse request
    print(f"Subscribing: {request.form['artist']}:{request.form['title']}")

    # add song 
    put_user_song(current_user.email, request.form['artist'], request.form['title']) 

    # redirect to music  
    return redirect(url_for('subscription.music'))

@bp.route('/music/query', methods=["POST"])
def query():

    # parse request
    print(f"Querying: {request.form['artist']}:{request.form['title']}:{request.form['year']}")

    # query db
    songs = get_songs(artist=request.form['artist'], title=request.form['title'], year=request.form['year'])

    # If we're local, use place holder images.
    if os.environ['FLASK_ENV'] == "dev":
            for song in songs:
                song.img_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Test-Logo.svg/783px-Test-Logo.svg.png"
    else:
        for song in songs:
            song.img_url = get_img(song.artist)

    query_songs = []

    for song in songs:
        query_songs.append({'artist': song.artist, 'title': song.title, 'year': song.year, 'web_url': song.web_url, 'img_url': song.img_url})

    session['query_songs'] = query_songs

    # redirect to music  
    return redirect(url_for('subscription.music'))

music/templates/authentication/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h3>Music Subscription App Login Page</h3>
    
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <div>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.submit(class_="btn btn-primary") }}
        </div>
    </form>

</div>
{% endblock %}

music/templates/authentication/register.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h3>Music Subscription App Registration Page</h3>
    
    <form action="" method="post" enctype="multipart/form-data" novalidate>
        {{ form.hidden_tag() }}
        <div>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.submit(class_="btn btn-primary") }}
        </div>
    </form>

</div>
{% endblock %}

music/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Cloud Computing - Assessment 2</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

      <a class="navbar-brand" href="#">Cloud Computing - Assessment 2</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{{ url_for('index')}}">Index</a>
          {% if not current_user.is_authenticated %}
          <a class="nav-item nav-link" href="{{ url_for('authentication.login')}}">Log In</a>
          <a class="nav-item nav-link" href="{{ url_for('authentication.register')}}">Register</a>
          {% else %}
          <a class="nav-item nav-link" href="{{ url_for('subscription.music')}}">Main</a>
          <a class="nav-item nav-link" href="{{ url_for('authentication.logout')}}">Log Out</a>
          {% endif %}
        </div>
    </nav>
    <!-- Your page content -->
    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

music/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h3>Task-1</h3>
    <h5>Music Subscription App</h5>
    Create a simple online music subscription application using AWS S3 and DynamoDB, and host it in a free-tier EC2 instance.
</div>
{% endblock %}

music/templates/subscription/music.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h3>Music Subscription App Main Page</h3>
    <h5>User area</h5>
    User: {{ current_user.username }}
    <h5>Subscription area</h5>
    {% for song in user_songs %}
    <div class="card">
        <div class="media">
            <img src="{{song.img_url}}" class="mr-3 img-thumbnail" width="100" alt="{{song.img_url}}">
            <div class="media-body">
                {{song.artist}}
                {{song.title}}
                {{song.year}}
                {{song.web_url}}
            </div>
            <form action="{{url_for('subscription.remove')}}" method="POST">
                <input type="hidden" value="{{song.artist}}" name="artist">
                <input type="hidden" value="{{song.title}}" name="title">
                <button type="submit"class="btn-primary">Remove</button>
            </form>
        </div>
    </div>
    {% endfor %}

    <h5>Query area</h5>
    <form action="{{url_for('subscription.query')}}" method="POST">
        {{ form.hidden_tag() }}
        <div>
            {{ form.artist.label }}<br>
            {{ form.artist(size=32) }}<br>
            {% for error in form.artist.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.title.label }}<br>
            {{ form.title(size=32) }}<br>
            {% for error in form.title.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.year.label }}<br>
            {{ form.year(size=32) }}<br>
            {% for error in form.year.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div>
            {{ form.search(class_="btn btn-primary") }}
        </div>
    </form>

    {% if session['query_songs']|length == 0 %}
            <div>No result is retrieved. Please query again.</div>
    {% endif %}
    {% for song in session.pop('query_songs', []) %}
        
        <div class="card">
            <div class="media">
                <img src="{{song['img_url']}}" class="mr-3 img-thumbnail" width="100" alt="{{song['img_url']}}">
                <div class="media-body">
                    {{song['artist']}}
                    {{song['title']}}
                    {{song['year']}}
                    {{song['web_url']}}
                </div>
                <form action="{{url_for('subscription.subscribe')}}" method="POST">
                    <input type="hidden" value="{{song['artist']}}" name="artist">
                    <input type="hidden" value="{{song['title']}}" name="title">
                    <button type="submit"class="btn-primary">Subscribe</button>
                </form>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}